// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrzewodnikSWPW.Web.Data;

#nullable disable

namespace PrzewodnikSWPW.Web.Data.Migrations
{
    [DbContext(typeof(PrzewodnikDbContext))]
    [Migration("20260928181619_DodajTozsamosc")]
    partial class DodajTozsamosc
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PrzewodnikSWPW.Web.Models.Budynek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adres")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("CzyAktywny")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("CzyMaWinde")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpisDostepnosciArchitektonicznej")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Kod")
                        .IsUnique()
                        .HasDatabaseName("UQ_Budynek_Kod");

                    b.ToTable("Budynek");
                });

            modelBuilder.Entity("PrzewodnikSWPW.Web.Models.Kierunek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Azymut")
                        .HasColumnType("int");

                    b.Property<bool>("CzyAktywny")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("CzyDostepnyBezSchodow")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("KierunekPowrotnyId")
                        .HasColumnType("int");

                    b.Property<string>("OpisPrzejscia")
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<int?>("PunktDocelowyId")
                        .HasColumnType("int");

                    b.Property<int>("PunktZrodlowyId")
                        .HasColumnType("int");

                    b.Property<byte>("RodzajPrzejscia")
                        .HasColumnType("tinyint");

                    b.Property<int?>("SalaDocelowaId")
                        .HasColumnType("int");

                    b.Property<decimal>("Waga")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("KierunekPowrotnyId");

                    b.HasIndex("PunktDocelowyId");

                    b.HasIndex("SalaDocelowaId");

                    b.HasIndex("PunktZrodlowyId", "Azymut")
                        .IsUnique()
                        .HasDatabaseName("UQ_Kierunek_Zrodlo_Azymut");

                    b.ToTable("Kierunek", t =>
                        {
                            t.HasCheckConstraint("CK_Kierunek_Azymut", "[Azymut] IN (0, 90, 180, 270)");

                            t.HasCheckConstraint("CK_Kierunek_BezPetli", "[PunktZrodlowyId] <> [PunktDocelowyId]");

                            t.HasCheckConstraint("CK_Kierunek_JedenCel", "([PunktDocelowyId] IS NOT NULL AND [SalaDocelowaId] IS NULL) OR ([PunktDocelowyId] IS NULL AND [SalaDocelowaId] IS NOT NULL)");

                            t.HasCheckConstraint("CK_Kierunek_Waga", "[Waga] > 0 AND [Waga] <= 200");
                        });
                });

            modelBuilder.Entity("PrzewodnikSWPW.Web.Models.ObszarAktywny", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Etykieta")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("KierunekId")
                        .HasColumnType("int");

                    b.Property<string>("Ksztalt")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Wspolrzedne")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<int>("ZdjecieId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KierunekId");

                    b.HasIndex("ZdjecieId");

                    b.ToTable("ObszarAktywny", t =>
                        {
                            t.HasCheckConstraint("CK_Obszar_Ksztalt", "[Ksztalt] IN ('rect', 'circle', 'poly')");
                        });
                });

            modelBuilder.Entity("PrzewodnikSWPW.Web.Models.Pietro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BudynekId")
                        .HasColumnType("int");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Numer")
                        .HasColumnType("int");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BudynekId", "Numer")
                        .IsUnique()
                        .HasDatabaseName("UQ_Pietro_Budynek_Numer");

                    b.ToTable("Pietro");
                });

            modelBuilder.Entity("PrzewodnikSWPW.Web.Models.PunktRuchu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AzymutDomyslny")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("CzyAktywny")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpisGlosowy")
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<int>("PietroId")
                        .HasColumnType("int");

                    b.Property<int>("TypPunktuId")
                        .HasColumnType("int");

                    b.Property<decimal?>("X")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.Property<decimal?>("Y")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9,2)");

                    b.HasKey("Id");

                    b.HasIndex("Kod")
                        .IsUnique()
                        .HasDatabaseName("UQ_PunktRuchu_Kod");

                    b.HasIndex("PietroId");

                    b.HasIndex("TypPunktuId");

                    b.ToTable("PunktRuchu", t =>
                        {
                            t.HasCheckConstraint("CK_PunktRuchu_Azymut", "[AzymutDomyslny] IN (0, 90, 180, 270)");
                        });
                });

            modelBuilder.Entity("PrzewodnikSWPW.Web.Models.PunktUdogodnienie", b =>
                {
                    b.Property<int>("PunktRuchuId")
                        .HasColumnType("int");

                    b.Property<int>("UdogodnienieId")
                        .HasColumnType("int");

                    b.Property<string>("Uwagi")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("PunktRuchuId", "UdogodnienieId");

                    b.HasIndex("UdogodnienieId");

                    b.ToTable("PunktUdogodnienie");
                });

            modelBuilder.Entity("PrzewodnikSWPW.Web.Models.Sala", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aliasy")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<bool>("CzyAktywna")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("CzyDostepnaDlaWozkow")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("LiczbaMiejsc")
                        .HasColumnType("int");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpisGlosowy")
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<int>("PietroId")
                        .HasColumnType("int");

                    b.Property<int?>("PunktWejsciowyId")
                        .HasColumnType("int");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TypSaliId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PunktWejsciowyId");

                    b.HasIndex("Symbol")
                        .HasDatabaseName("IX_Sala_Symbol");

                    b.HasIndex("TypSaliId");

                    b.HasIndex("PietroId", "Symbol")
                        .IsUnique()
                        .HasDatabaseName("UQ_Sala_Pietro_Symbol");

                    b.ToTable("Sala");
                });

            modelBuilder.Entity("PrzewodnikSWPW.Web.Models.SalaUdogodnienie", b =>
                {
                    b.Property<int>("SalaId")
                        .HasColumnType("int");

                    b.Property<int>("UdogodnienieId")
                        .HasColumnType("int");

                    b.Property<string>("Uwagi")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("SalaId", "UdogodnienieId");

                    b.HasIndex("UdogodnienieId");

                    b.ToTable("SalaUdogodnienie");
                });

            modelBuilder.Entity("PrzewodnikSWPW.Web.Models.TypPunktu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Opis")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Nazwa")
                        .IsUnique()
                        .HasDatabaseName("UQ_TypPunktu_Nazwa");

                    b.ToTable("TypPunktu");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nazwa = "Hol",
                            Opis = "Otwarta przestrzeń wejściowa"
                        },
                        new
                        {
                            Id = 2,
                            Nazwa = "Korytarz",
                            Opis = "Odcinek korytarza"
                        },
                        new
                        {
                            Id = 3,
                            Nazwa = "Skrzyżowanie",
                            Opis = "Miejsce, w którym korytarze się krzyżują"
                        },
                        new
                        {
                            Id = 4,
                            Nazwa = "Podest schodów",
                            Opis = "Spocznik przy biegu schodów"
                        },
                        new
                        {
                            Id = 5,
                            Nazwa = "Przed windą",
                            Opis = "Miejsce przed drzwiami windy"
                        });
                });

            modelBuilder.Entity("PrzewodnikSWPW.Web.Models.TypSali", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Opis")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Nazwa")
                        .IsUnique()
                        .HasDatabaseName("UQ_TypSali_Nazwa");

                    b.ToTable("TypSali");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nazwa = "Sala komputerowa",
                            Opis = "Pracownia ze stanowiskami komputerowymi"
                        },
                        new
                        {
                            Id = 2,
                            Nazwa = "Sala ćwiczeniowa",
                            Opis = "Sala do zajęć ćwiczeniowych"
                        },
                        new
                        {
                            Id = 3,
                            Nazwa = "Sekretariat",
                            Opis = "Sekretariat lub dziekanat"
                        },
                        new
                        {
                            Id = 4,
                            Nazwa = "Sala wykładowa",
                            Opis = "Duża sala wykładowa"
                        },
                        new
                        {
                            Id = 5,
                            Nazwa = "Toaleta",
                            Opis = "Toaleta"
                        },
                        new
                        {
                            Id = 6,
                            Nazwa = "Pomieszczenie techniczne",
                            Opis = "Niedostępne dla studentów"
                        });
                });

            modelBuilder.Entity("PrzewodnikSWPW.Web.Models.Udogodnienie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ikona")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Opis")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.HasKey("Id");

                    b.HasIndex("Nazwa")
                        .IsUnique()
                        .HasDatabaseName("UQ_Udogodnienie_Nazwa");

                    b.ToTable("Udogodnienie");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ikona = "elevator",
                            Nazwa = "Winda",
                            Opis = "Winda osobowa z sygnalizacją głosową"
                        },
                        new
                        {
                            Id = 2,
                            Ikona = "ramp",
                            Nazwa = "Pochylnia",
                            Opis = "Podjazd dla wózków"
                        },
                        new
                        {
                            Id = 3,
                            Ikona = "hearing",
                            Nazwa = "Pętla indukcyjna",
                            Opis = "Wspomaganie aparatów słuchowych"
                        },
                        new
                        {
                            Id = 4,
                            Ikona = "braille",
                            Nazwa = "Oznaczenia brajlowskie",
                            Opis = "Tabliczki z pismem Braille'a"
                        },
                        new
                        {
                            Id = 5,
                            Ikona = "path",
                            Nazwa = "Ścieżka dotykowa",
                            Opis = "Prowadząca faktura w posadzce"
                        },
                        new
                        {
                            Id = 6,
                            Ikona = "contrast",
                            Nazwa = "Oznaczenie kontrastowe",
                            Opis = "Kontrastowe oznaczenie krawędzi"
                        });
                });

            modelBuilder.Entity("PrzewodnikSWPW.Web.Models.Utrudnienie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataUtworzenia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<int?>("KierunekId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ObowiazujeDo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ObowiazujeOd")
                        .HasColumnType("datetime2");

                    b.Property<string>("Przyczyna")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<int?>("PunktRuchuId")
                        .HasColumnType("int");

                    b.Property<string>("UtworzylId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("KierunekId");

                    b.HasIndex("PunktRuchuId");

                    b.ToTable("Utrudnienie", t =>
                        {
                            t.HasCheckConstraint("CK_Utrudnienie_Cel", "([KierunekId] IS NOT NULL AND [PunktRuchuId] IS NULL) OR ([KierunekId] IS NULL AND [PunktRuchuId] IS NOT NULL)");

                            t.HasCheckConstraint("CK_Utrudnienie_Daty", "[ObowiazujeDo] IS NULL OR [ObowiazujeDo] > [ObowiazujeOd]");
                        });
                });

            modelBuilder.Entity("PrzewodnikSWPW.Web.Models.WpisAudytu", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataOperacji")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("Encja")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("KluczEncji")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Operacja")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("UzytkownikId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("WartosciNowe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WartosciStare")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DataOperacji")
                        .IsDescending()
                        .HasDatabaseName("IX_WpisAudytu_Data");

                    b.ToTable("WpisAudytu");
                });

            modelBuilder.Entity("PrzewodnikSWPW.Web.Models.ZapytanieTrasy", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("CzasMs")
                        .HasColumnType("int");

                    b.Property<bool>("CzySukces")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataZapytania")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<decimal?>("DlugoscMetry")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("FrazaDo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FrazaZ")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("LiczbaKrokow")
                        .HasColumnType("int");

                    b.Property<int?>("SalaDoId")
                        .HasColumnType("int");

                    b.Property<int?>("SalaZId")
                        .HasColumnType("int");

                    b.Property<bool>("TrybWindy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("SalaDoId");

                    b.HasIndex("SalaZId");

                    b.HasIndex("CzySukces", "DataZapytania")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_ZapytanieTrasy_Sukces");

                    b.ToTable("ZapytanieTrasy");
                });

            modelBuilder.Entity("PrzewodnikSWPW.Web.Models.Zdjecie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CzyDekoracyjne")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("Kolejnosc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Licencja")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OpisRozszerzony")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PunktRuchuId")
                        .HasColumnType("int");

                    b.Property<int?>("SalaId")
                        .HasColumnType("int");

                    b.Property<string>("SciezkaPliku")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<string>("TekstAlternatywny")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Zrodlo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("PunktRuchuId");

                    b.HasIndex("SalaId");

                    b.ToTable("Zdjecie", t =>
                        {
                            t.HasCheckConstraint("CK_Zdjecie_Alt", "[CzyDekoracyjne] = 1 OR LEN(LTRIM(RTRIM([TekstAlternatywny]))) >= 5");

                            t.HasCheckConstraint("CK_Zdjecie_Wlasciciel", "([PunktRuchuId] IS NOT NULL AND [SalaId] IS NULL) OR ([PunktRuchuId] IS NULL AND [SalaId] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("PrzewodnikSWPW.Web.Models.ZgloszenieDostepnosci", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdresStrony")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("DataOdpowiedzi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataZgloszenia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ImieNazwisko")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ObslugujeId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Odpowiedz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.Property<string>("Telefon")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Tresc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ZgloszenieDostepnosci");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PrzewodnikSWPW.Web.Models.Kierunek", b =>
                {
                    b.HasOne("PrzewodnikSWPW.Web.Models.Kierunek", "KierunekPowrotny")
                        .WithMany()
                        .HasForeignKey("KierunekPowrotnyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PrzewodnikSWPW.Web.Models.PunktRuchu", "PunktDocelowy")
                        .WithMany("KierunkiPrzychodzace")
                        .HasForeignKey("PunktDocelowyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PrzewodnikSWPW.Web.Models.PunktRuchu", "PunktZrodlowy")
                        .WithMany("KierunkiWychodzace")
                        .HasForeignKey("PunktZrodlowyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrzewodnikSWPW.Web.Models.Sala", "SalaDocelowa")
                        .WithMany("KierunkiDoSali")
                        .HasForeignKey("SalaDocelowaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("KierunekPowrotny");

                    b.Navigation("PunktDocelowy");

                    b.Navigation("PunktZrodlowy");

                    b.Navigation("SalaDocelowa");
                });

            modelBuilder.Entity("PrzewodnikSWPW.Web.Models.ObszarAktywny", b =>
                {
                    b.HasOne("PrzewodnikSWPW.Web.Models.Kierunek", "Kierunek")
                        .WithMany("ObszaryAktywne")
                        .HasForeignKey("KierunekId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrzewodnikSWPW.Web.Models.Zdjecie", "Zdjecie")
                        .WithMany("ObszaryAktywne")
                        .HasForeignKey("ZdjecieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kierunek");

                    b.Navigation("Zdjecie");
                });

            modelBuilder.Entity("PrzewodnikSWPW.Web.Models.Pietro", b =>
                {
                    b.HasOne("PrzewodnikSWPW.Web.Models.Budynek", "Budynek")
                        .WithMany("Pietra")
                        .HasForeignKey("BudynekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Budynek");
                });

            modelBuilder.Entity("PrzewodnikSWPW.Web.Models.PunktRuchu", b =>
                {
                    b.HasOne("PrzewodnikSWPW.Web.Models.Pietro", "Pietro")
                        .WithMany("PunktyRuchu")
                        .HasForeignKey("PietroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrzewodnikSWPW.Web.Models.TypPunktu", "TypPunktu")
                        .WithMany("PunktyRuchu")
                        .HasForeignKey("TypPunktuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pietro");

                    b.Navigation("TypPunktu");
                });

            modelBuilder.Entity("PrzewodnikSWPW.Web.Models.PunktUdogodnienie", b =>
                {
                    b.HasOne("PrzewodnikSWPW.Web.Models.PunktRuchu", "PunktRuchu")
                        .WithMany("PunktUdogodnienia")
                        .HasForeignKey("PunktRuchuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrzewodnikSWPW.Web.Models.Udogodnienie", "Udogodnienie")
                        .WithMany("PunktUdogodnienia")
                        .HasForeignKey("UdogodnienieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PunktRuchu");

                    b.Navigation("Udogodnienie");
                });

            modelBuilder.Entity("PrzewodnikSWPW.Web.Models.Sala", b =>
                {
                    b.HasOne("PrzewodnikSWPW.Web.Models.Pietro", "Pietro")
                        .WithMany("Sale")
                        .HasForeignKey("PietroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrzewodnikSWPW.Web.Models.PunktRuchu", "PunktWejsciowy")
                        .WithMany()
                        .HasForeignKey("PunktWejsciowyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PrzewodnikSWPW.Web.Models.TypSali", "TypSali")
                        .WithMany("Sale")
                        .HasForeignKey("TypSaliId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pietro");

                    b.Navigation("PunktWejsciowy");

                    b.Navigation("TypSali");
                });

            modelBuilder.Entity("PrzewodnikSWPW.Web.Models.SalaUdogodnienie", b =>
                {
                    b.HasOne("PrzewodnikSWPW.Web.Models.Sala", "Sala")
                        .WithMany("SalaUdogodnienia")
                        .HasForeignKey("SalaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrzewodnikSWPW.Web.Models.Udogodnienie", "Udogodnienie")
                        .WithMany("SalaUdogodnienia")
                        .HasForeignKey("UdogodnienieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sala");

                    b.Navigation("Udogodnienie");
                });

            modelBuilder.Entity("PrzewodnikSWPW.Web.Models.Utrudnienie", b =>
                {
                    b.HasOne("PrzewodnikSWPW.Web.Models.Kierunek", "Kierunek")
                        .WithMany("Utrudnienia")
                        .HasForeignKey("KierunekId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PrzewodnikSWPW.Web.Models.PunktRuchu", "PunktRuchu")
                        .WithMany("Utrudnienia")
                        .HasForeignKey("PunktRuchuId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Kierunek");

                    b.Navigation("PunktRuchu");
                });

            modelBuilder.Entity("PrzewodnikSWPW.Web.Models.ZapytanieTrasy", b =>
                {
                    b.HasOne("PrzewodnikSWPW.Web.Models.Sala", "SalaDo")
                        .WithMany()
                        .HasForeignKey("SalaDoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PrzewodnikSWPW.Web.Models.Sala", "SalaZ")
                        .WithMany()
                        .HasForeignKey("SalaZId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("SalaDo");

                    b.Navigation("SalaZ");
                });

            modelBuilder.Entity("PrzewodnikSWPW.Web.Models.Zdjecie", b =>
                {
                    b.HasOne("PrzewodnikSWPW.Web.Models.PunktRuchu", "PunktRuchu")
                        .WithMany("Zdjecia")
                        .HasForeignKey("PunktRuchuId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PrzewodnikSWPW.Web.Models.Sala", "Sala")
                        .WithMany("Zdjecia")
                        .HasForeignKey("SalaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PunktRuchu");

                    b.Navigation("Sala");
                });

            modelBuilder.Entity("PrzewodnikSWPW.Web.Models.Budynek", b =>
                {
                    b.Navigation("Pietra");
                });

            modelBuilder.Entity("PrzewodnikSWPW.Web.Models.Kierunek", b =>
                {
                    b.Navigation("ObszaryAktywne");

                    b.Navigation("Utrudnienia");
                });

            modelBuilder.Entity("PrzewodnikSWPW.Web.Models.Pietro", b =>
                {
                    b.Navigation("PunktyRuchu");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("PrzewodnikSWPW.Web.Models.PunktRuchu", b =>
                {
                    b.Navigation("KierunkiPrzychodzace");

                    b.Navigation("KierunkiWychodzace");

                    b.Navigation("PunktUdogodnienia");

                    b.Navigation("Utrudnienia");

                    b.Navigation("Zdjecia");
                });

            modelBuilder.Entity("PrzewodnikSWPW.Web.Models.Sala", b =>
                {
                    b.Navigation("KierunkiDoSali");

                    b.Navigation("SalaUdogodnienia");

                    b.Navigation("Zdjecia");
                });

            modelBuilder.Entity("PrzewodnikSWPW.Web.Models.TypPunktu", b =>
                {
                    b.Navigation("PunktyRuchu");
                });

            modelBuilder.Entity("PrzewodnikSWPW.Web.Models.TypSali", b =>
                {
                    b.Navigation("Sale");
                });

            modelBuilder.Entity("PrzewodnikSWPW.Web.Models.Udogodnienie", b =>
                {
                    b.Navigation("PunktUdogodnienia");

                    b.Navigation("SalaUdogodnienia");
                });

            modelBuilder.Entity("PrzewodnikSWPW.Web.Models.Zdjecie", b =>
                {
                    b.Navigation("ObszaryAktywne");
                });
#pragma warning restore 612, 618
        }
    }
}
